### ISSUE TITLE
TEAM application crashing when creating an Eligibility Policy 

### ISSUE THREAD

**Issue by vgsachin839** [aws-samples/iam-identity-center-team#261]
**Describe the bug**
We have deployed the TEAM application in our LZ Organization, which is having more than 1000+ AWS accounts and 750+ permission sets in Identity Center. When we are trying to create an eligibility policy, UI is crashing, and we are seeing the errors in Developer Tools console in browser. We tested with both Chrome and Edge.

Is it due to the volume of accounts and permission sets, this issue is happening ?

**Expected behavior**
Data like Org accounts, OUs and Permission Sets should be loaded successfully in the Eligibility Policy screen.

**Screenshots**
![Eligibility_Policy_Error](https://github.com/aws-samples/iam-identity-center-team/assets/100936221/ae1ba4a2-278e-4c9e-88e5-6f625e724400)

![Eligibility_Policy_Error_2](https://github.com/aws-samples/iam-identity-center-team/assets/100936221/1bc25966-3ba4-4432-981c-2bf36dd77ee6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 
- OS: Windows 11
 - Browser: Edge
 - Version: Edge Version 125.0.2535.85 (Official build) (64-bit)

**Comment by AlDawoode** [comment]
Hi,
I'm facing similar issue when creating an Eligibilty Policy.
The UI doesn't crach directly when i click on "Create eligibility policy", but it does after 20 second where it can't load AWS OUs
![image](https://github.com/aws-samples/iam-identity-center-team/assets/38096714/956fdcbe-a80a-433a-9706-5bbb86f0d343)

**Comment by AlDawoode** [comment]
For now i fixed my issue by the following steps:
- I print out the error msg in the console when the UI crash
![image](https://github.com/aws-samples/iam-identity-center-team/assets/38096714/ee976443-1161-4218-835b-4faf475e9f8e)

- I checked the lambda that fetch the AWS OUs and it work fine **BUT** it just take time because i have a big number of OUs so lambda does take 44 seconds in my case.

- That Frontend part (ReactJS) make a request to the backend (AWS AppSync) it is just an api that invoke lambda function and return the response back to the frontend

So the issue comming from AppSunc
It turns out that Appsync has a 30 second hard limit for request execution time for mutations, queries, and subscriptions. 
Please refer to the [Appsync documentation](https://docs.aws.amazon.com/general/latest/gr/appsync.html#limits_appsync) for this limit. 
Unfortunately, this means that there is no configuration or setting which will allow us to exceed this limit.

If you have a query that is taking more than 30 seconds, then the workaround is to implement this in an asynchronous manner. Please refer to this blog for a strategy in [Implementing a long-running query on AWS AppSync](https://aws.amazon.com/blogs/mobile/invoke-aws-services-directly-from-aws-appsync/)

The above suggestion solution will take much time and effort for me to do.. 
AWS Should re-implement the way of fetching OUs, Groups, Useres, and Permission Sets by following the above suesstion or coming with better one.

- For now, my workaround involved updating the lambda function (teamgetOUs/src/index.py) to return a list of specific OUs, either dynamically generated or hardcoded.

**Comment by AlDawoode** [comment]
@tawoyinfa 
The first bug i was facing is the one you mentioned https://github.com/aws-samples/iam-identity-center-team/issues/236 :)
and i followed your workaround suggestion you mentioned there ..

**Comment by tawoyinfa** [comment]
@vgsachin839  this issue has been fixed in the latest release. Follow the guidance in [the documentation](https://aws-samples.github.io/iam-identity-center-team/docs/deployment/update.html#if-upgrading-to-v112) to upgrade to the latest version

**Comment by vgsachin839** [comment]
@tawoyinfa I see that the issue is still not fixed even after upgrading the solution to 1.1.2. I think you have fixed the getOUs issue mentioned in issues #235, but we are still facing issue with getPermissions while creating the Eligibility policy.

![Eligibility_Policy_Error_28Jun2024](https://github.com/aws-samples/iam-identity-center-team/assets/100936221/fdab9d50-1e3a-4729-ab58-d7548f1f0602)
