### ISSUE TITLE
Unable to open the "Eligibility policy" page, stack on white, empty screen 

### ISSUE THREAD

**Issue by adamkpn** [aws-samples/iam-identity-center-team#57]
**Describe the bug**
After deploying the "Temporary Elevated Access Management" entering into the application as Administrator and then clicking the "Eligibility Policy" link on the left, a blank screen is opened
(Important: Also tested from Chrome and Safari and the effect is the same)

Debugging with the Developer tools (Firefox), I receive the following errors in the Console:
`Refused to apply style from 'https://main.xxxxxxxxxxxxxxx.amplifyapp.com/index.html' because its MIME type('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`
`The resource from “https://main.xxxxxxxxxxxxxxx.amplifyapp.com/index.html” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

**To Reproduce**
1. Go to the 'TEAM' application from the "IAM Identity Center" page
2. Click on 'Eligibility policy'
3. See the blank screen

**Expected behavior**
Menu with the ability to add new Policy

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 116.0.2

**Comment by tawoyinfa** [comment]
@adamkpn have you tried signing out and signing back into the TEAM application as admin ?

**Comment by adamkpn** [comment]
@tawoyinfa my user is already in Team-Administrators groups so I did logout/login with my user account but it didn't help.

As I know there is no local Admin user.

**Comment by stevenpitts** [comment]
@adamkpn Could this be re-opened? There's a workaround, but it's still a bug.

**Comment by trickyearlobe** [comment]
> @adamkpn Could this be re-opened? There's a workaround, but it's still a bug.

+1
I ran into the same bug

**Comment by tawoyinfa** [comment]
@trickyearlobe  The issue has been fixed in https://github.com/aws-samples/iam-identity-center-team/commit/ba8366ebdd10b43b813b43ef3e1dfaa0c486b953. Follow the steps in the [update documentation](https://aws-samples.github.io/iam-identity-center-team/docs/deployment/update.html) to deploy the latest version

**Comment by adziura-ledger** [comment]
@tawoyinfa 
Have just run into the same issue.
So, it's not fixed (v1.1.0)
